[package]
name = "api"
version = "0.1.0"
authors.workspace = true
description.workspace = true
edition.workspace = true

[dependencies]
axum = { version = "0.7.9", features = ["macros"] }
tokio = { version = "1.41.1", features = ["full"] }
# hyper = { version = "1.5.1", features = ["full"] }
# tower = "0.5.1"

listenfd = { version = "1.0.1", optional = true }

serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"

easy-dynamodb = "0.1.6"
slog = "2.7.0"
tracing = "0.1.40"

thiserror = "2.0.3"

tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }

models.workspace = true
uuid = { version = "1.11.0", features = ["v4"] }
by-axum = "0.1.2"


[features]
default = []
reload = ["listenfd"]
lambda = ["by-axum/lambda"]