[package]
name = "models"
version.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true

[dependencies]
chrono.workspace = true
serde = { workspace = true, features = ["derive"] }
dioxus-translate.workspace = true
by-macros.workspace = true
schemars = "0.8.21"
thiserror = "2.0.11"
serde_json.workspace = true
uuid = { version = "1.12.1", features = ["v4"] }
serde_urlencoded = "0.7.1"

# Server dependencies
sqlx = { workspace = true, optional = true }
by-axum = { workspace = true, optional = true }

[features]
web = ["dioxus-translate/web"]
server = ["by-axum", "by-macros/server"]
