[workspace]
members = ["package/models", "package/api", "platform"]
resolver = "1"

[workspace.package]
version = "1.0.0"
authors = ["Biyard"]
description = "iitp"
edition = "2021"

[workspace.dependencies]
models = { version = "1.0.0", path = "package/models" }
