[package]
name = "platform"
version = "0.1.0"
authors = ["victor138128 <yepp0517@naver.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.197", features = ["derive"] }
dioxus = { version = "0.6.0-alpha.3", features = ["default", "fullstack", "router"] }
chrono = "0.4"
dioxus-aws = { version = "0.6.2" }

dioxus-logger = "0.5.1"
easy-dynamodb = { version = "0.1.6", optional = true }
slog = { version = "2.7.0", optional = true }

[features]
default = []
server = ["dioxus-aws/server", "easy-dynamodb", "slog"]
lambda = ["dioxus-aws/lambda", "server"]
web = ["dioxus-aws/web"]
