[package]
name = "main-ui"
version = "0.2.7"
authors.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Rust Sdk Dependencies
by-components.workspace = true
dioxus-translate.workspace = true
dioxus-aws.workspace = true
easy-dynamodb = { workspace = true, optional = true }
by-types.workspace = true
rest-api.workspace = true

# This Repo Dependencies
models.workspace = true

# Dioxus Dependencies
dioxus = { workspace = true, features = ["default", "fullstack", "router"] }

serde = { version = "1.0.197", features = ["derive"] }
chrono = "0.4"
reqwest = { version = "0.12.5", features = ["blocking", "json"] }
dioxus-logger = "0.5.1"
slog = { version = "2.7.0" }
slog-term = { version = "2.9.1", optional = true }
aws-config = { version = "1.1.7", features = [
  "behavior-version-latest",
], optional = true }
aws-sdk-sesv2 = { version = "1.52.0", optional = true }
aws-sdk-dynamodb = { version = "1.39.0", features = [
  "behavior-version-latest",
], optional = true }
regex = "1.3.9"
rand = { version = "0.8.5", optional = true }
static_str_ops = { version = "0.1.2", optional = true }
sha3 = "0.10.8"
urlencoding = { version = "2.1.3", optional = true }
axum = { version = "0.7.9", optional = true }
wasm-bindgen = { version = "0.2.100", optional = true }
wasm-bindgen-futures = { version = "0.4.49", optional = true }
web-sys = { version = "0.3.74", optional = true }
getrandom = { version = "0.2", features = ["js"] }

[features]
default = []
server = [
  "dioxus-aws/server",
  "easy-dynamodb",
  "aws-config",
  "aws-sdk-sesv2",
  "rand",
  "aws-sdk-dynamodb",
  "slog-term",
  "static_str_ops",
  "urlencoding",
  "axum",
  "models/server",
]
lambda = ["dioxus-aws/lambda", "server"]
web = [
  "dioxus-aws/web",
  "dioxus-translate/web",
  "by-components/web",
  "web-sys",
  "wasm-bindgen",
  "wasm-bindgen-futures",
  "models/web",
]
static_str_ops = ["dep:static_str_ops"]
